# How to start docker compose setup with this configuration:
# COMPOSE_FILE=compose.yaml:compose.bvngeedotcom.yaml REGISTRY_URL="registry.bvngee.com/" docker compose up -d

services:
  caddy:
    ports: !override []
    expose:
      - "80"
      - "443"
      - "443/udp"
    networks:
      - default
      - bvngeedotcom-host_external

networks:
  bvngeedotcom-host_external:
    external: true
