name: Docker Image CI

on:
  push:
    branches: [ "prod" ]

env:
  REGISTRY_URL: "${{ secrets.CONTAINER_REGISTRY_URL }}"
  
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login $REGISTRY_URL -u "${{ secrets.CONTAINER_REGISTRY_USERNAME }}" --password-stdin
    - run: docker compose build
    - run: docker compose push
